import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateInventoryTables1758237600000 implements MigrationInterface {
  name = 'CreateInventoryTables1758237600000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create Warehouse table
    await queryRunner.query(`
      CREATE TABLE \`tabWarehouse\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`warehouseType\` enum('Transit', 'Internal', 'External') NOT NULL DEFAULT 'Internal',
        \`parentWarehouse\` varchar(140) NULL,
        \`isGroup\` tinyint NOT NULL DEFAULT 0,
        \`disabled\` tinyint NOT NULL DEFAULT 0,
        \`company\` varchar(140) NULL,
        \`account\` varchar(140) NULL,
        \`emailId\` varchar(140) NULL,
        \`phoneNo\` varchar(140) NULL,
        \`mobileNo\` varchar(140) NULL,
        \`addressLine1\` varchar(140) NULL,
        \`addressLine2\` varchar(140) NULL,
        \`city\` varchar(140) NULL,
        \`state\` varchar(140) NULL,
        \`pincode\` varchar(140) NULL,
        \`country\` varchar(140) NULL,
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        UNIQUE INDEX \`IDX_warehouse_name\` (\`name\`),
        INDEX \`IDX_warehouse_tenant_id\` (\`tenant_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_warehouse_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    // Create Bin table
    await queryRunner.query(`
      CREATE TABLE \`tabBin\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`item_code\` varchar(140) NOT NULL,
        \`warehouse\` varchar(140) NOT NULL,
        \`actual_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`planned_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`indented_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`ordered_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`reserved_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`reserved_qty_for_production\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`reserved_qty_for_sub_contract\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`projected_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`valuation_rate\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`stock_value\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        \`item_id\` varchar(36) NULL,
        \`warehouse_id\` varchar(36) NULL,
        UNIQUE INDEX \`IDX_bin_item_warehouse\` (\`item_code\`, \`warehouse\`),
        INDEX \`IDX_bin_tenant_id\` (\`tenant_id\`),
        INDEX \`IDX_bin_item_id\` (\`item_id\`),
        INDEX \`IDX_bin_warehouse_id\` (\`warehouse_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_bin_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_bin_item\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_bin_warehouse\` FOREIGN KEY (\`warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    // Create Batch table
    await queryRunner.query(`
      CREATE TABLE \`tabBatch\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`item\` varchar(140) NOT NULL,
        \`batch_id\` varchar(140) NOT NULL,
        \`batch_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`stock_uom\` varchar(140) NULL,
        \`manufacturing_date\` date NULL,
        \`expiry_date\` date NULL,
        \`supplier\` varchar(140) NULL,
        \`reference_doctype\` varchar(140) NULL,
        \`reference_name\` varchar(140) NULL,
        \`description\` text NULL,
        \`disabled\` tinyint NOT NULL DEFAULT 0,
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        \`item_id\` varchar(36) NULL,
        UNIQUE INDEX \`IDX_batch_name\` (\`name\`),
        INDEX \`IDX_batch_tenant_id\` (\`tenant_id\`),
        INDEX \`IDX_batch_item_id\` (\`item_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_batch_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_batch_item\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    // Create Serial No table
    await queryRunner.query(`
      CREATE TABLE \`tabSerialNo\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`serial_no\` varchar(140) NOT NULL,
        \`item_code\` varchar(140) NOT NULL,
        \`item_name\` varchar(140) NULL,
        \`description\` text NULL,
        \`warehouse\` varchar(140) NULL,
        \`company\` varchar(140) NULL,
        \`status\` enum('Active', 'Inactive', 'Delivered', 'Expired') NOT NULL DEFAULT 'Active',
        \`supplier\` varchar(140) NULL,
        \`customer\` varchar(140) NULL,
        \`delivery_date\` date NULL,
        \`purchase_date\` date NULL,
        \`purchase_rate\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`purchase_document_type\` varchar(140) NULL,
        \`purchase_document_no\` varchar(140) NULL,
        \`warranty_period\` int NULL,
        \`warranty_expiry_date\` date NULL,
        \`amc_expiry_date\` date NULL,
        \`maintenance_status\` varchar(140) NULL,
        \`maintenance_required\` tinyint NOT NULL DEFAULT 0,
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        \`item_id\` varchar(36) NULL,
        \`warehouse_id\` varchar(36) NULL,
        UNIQUE INDEX \`IDX_serial_no_name\` (\`name\`),
        UNIQUE INDEX \`IDX_serial_no_serial\` (\`serial_no\`),
        INDEX \`IDX_serial_no_tenant_id\` (\`tenant_id\`),
        INDEX \`IDX_serial_no_item_id\` (\`item_id\`),
        INDEX \`IDX_serial_no_warehouse_id\` (\`warehouse_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_serial_no_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_serial_no_item\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_serial_no_warehouse\` FOREIGN KEY (\`warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    // Create Stock Entry table
    await queryRunner.query(`
      CREATE TABLE \`tabStockEntry\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`naming_series\` varchar(140) NULL,
        \`stock_entry_type\` enum('Material Issue', 'Material Receipt', 'Material Transfer', 'Material Transfer for Manufacture', 'Manufacture', 'Repack', 'Send to Subcontractor') NOT NULL DEFAULT 'Material Issue',
        \`purpose\` enum('Material Issue', 'Material Receipt', 'Material Transfer', 'Material Transfer for Manufacture', 'Manufacture', 'Repack', 'Send to Subcontractor') NOT NULL DEFAULT 'Material Issue',
        \`company\` varchar(140) NULL,
        \`posting_date\` date NOT NULL,
        \`posting_time\` time NOT NULL,
        \`set_posting_time\` tinyint NOT NULL DEFAULT 0,
        \`inspection_required\` tinyint NOT NULL DEFAULT 0,
        \`apply_putaway_rule\` tinyint NOT NULL DEFAULT 0,
        \`from_bom\` tinyint NOT NULL DEFAULT 0,
        \`use_multi_level_bom\` tinyint NOT NULL DEFAULT 1,
        \`bom_no\` varchar(140) NULL,
        \`fg_completed_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`process_loss_percentage\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`process_loss_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`from_warehouse\` varchar(140) NULL,
        \`to_warehouse\` varchar(140) NULL,
        \`scan_barcode\` varchar(140) NULL,
        \`total_outgoing_value\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`total_incoming_value\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`value_difference\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`total_additional_costs\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`supplier\` varchar(140) NULL,
        \`supplier_name\` varchar(140) NULL,
        \`supplier_address\` varchar(140) NULL,
        \`address_display\` text NULL,
        \`project\` varchar(140) NULL,
        \`select_print_heading\` varchar(140) NULL,
        \`letter_head\` varchar(140) NULL,
        \`remarks\` text NULL,
        \`per_transferred\` decimal(6,2) NOT NULL DEFAULT '0.00',
        \`total_amount\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`job_card\` varchar(140) NULL,
        \`work_order\` varchar(140) NULL,
        \`purchase_order\` varchar(140) NULL,
        \`delivery_note_no\` varchar(140) NULL,
        \`sales_invoice_no\` varchar(140) NULL,
        \`pick_list\` varchar(140) NULL,
        \`credit_note\` varchar(140) NULL,
        \`is_opening\` enum('No', 'Yes') NOT NULL DEFAULT 'No',
        \`add_to_transit\` tinyint NOT NULL DEFAULT 0,
        \`outgoing_stock_entry\` varchar(140) NULL,
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        \`from_warehouse_id\` varchar(36) NULL,
        \`to_warehouse_id\` varchar(36) NULL,
        \`work_order_id\` varchar(36) NULL,
        UNIQUE INDEX \`IDX_stock_entry_name\` (\`name\`),
        INDEX \`IDX_stock_entry_tenant_id\` (\`tenant_id\`),
        INDEX \`IDX_stock_entry_from_warehouse_id\` (\`from_warehouse_id\`),
        INDEX \`IDX_stock_entry_to_warehouse_id\` (\`to_warehouse_id\`),
        INDEX \`IDX_stock_entry_work_order_id\` (\`work_order_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_stock_entry_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_from_warehouse\` FOREIGN KEY (\`from_warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_to_warehouse\` FOREIGN KEY (\`to_warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_work_order\` FOREIGN KEY (\`work_order_id\`) REFERENCES \`work_orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    // Create Stock Entry Detail table
    await queryRunner.query(`
      CREATE TABLE \`tabStockEntryDetail\` (
        \`id\` varchar(36) NOT NULL,
        \`name\` varchar(140) NOT NULL,
        \`item_code\` varchar(140) NOT NULL,
        \`item_name\` varchar(140) NULL,
        \`description\` text NULL,
        \`item_group\` varchar(140) NULL,
        \`image\` varchar(140) NULL,
        \`qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`transfer_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`uom\` varchar(140) NULL,
        \`stock_uom\` varchar(140) NULL,
        \`conversion_factor\` decimal(18,6) NOT NULL DEFAULT '1.000000',
        \`s_warehouse\` varchar(140) NULL,
        \`t_warehouse\` varchar(140) NULL,
        \`finished_item\` varchar(140) NULL,
        \`is_finished_item\` tinyint NOT NULL DEFAULT 0,
        \`is_scrap_item\` tinyint NOT NULL DEFAULT 0,
        \`original_item\` varchar(140) NULL,
        \`allow_zero_valuation_rate\` tinyint NOT NULL DEFAULT 0,
        \`set_basic_rate_manually\` tinyint NOT NULL DEFAULT 0,
        \`allow_alternative_item\` tinyint NOT NULL DEFAULT 0,
        \`basic_rate\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`basic_amount\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`additional_cost\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`valuation_rate\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`amount\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`expense_account\` varchar(140) NULL,
        \`cost_center\` varchar(140) NULL,
        \`project\` varchar(140) NULL,
        \`actual_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`transferred_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`bom_no\` varchar(140) NULL,
        \`material_request\` varchar(140) NULL,
        \`material_request_item\` varchar(140) NULL,
        \`original_item_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`picked_qty\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`serial_no\` text NULL,
        \`batch_no\` varchar(140) NULL,
        \`retain_sample\` tinyint NOT NULL DEFAULT 0,
        \`sample_quantity\` decimal(18,6) NOT NULL DEFAULT '0.000000',
        \`reference_purchase_receipt\` varchar(140) NULL,
        \`po_detail\` varchar(140) NULL,
        \`against_stock_entry\` varchar(140) NULL,
        \`ste_detail\` varchar(140) NULL,
        \`putaway_rule\` varchar(140) NULL,
        \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`modified_by\` varchar(140) NULL,
        \`owner\` varchar(140) NULL,
        \`docstatus\` int NOT NULL DEFAULT '0',
        \`idx\` varchar(140) NULL,
        \`tenant_id\` varchar(36) NOT NULL,
        \`stock_entry_id\` varchar(36) NOT NULL,
        \`item_id\` varchar(36) NULL,
        \`source_warehouse_id\` varchar(36) NULL,
        \`target_warehouse_id\` varchar(36) NULL,
        \`batch_id\` varchar(36) NULL,
        INDEX \`IDX_stock_entry_detail_tenant_id\` (\`tenant_id\`),
        INDEX \`IDX_stock_entry_detail_stock_entry_id\` (\`stock_entry_id\`),
        INDEX \`IDX_stock_entry_detail_item_id\` (\`item_id\`),
        INDEX \`IDX_stock_entry_detail_source_warehouse_id\` (\`source_warehouse_id\`),
        INDEX \`IDX_stock_entry_detail_target_warehouse_id\` (\`target_warehouse_id\`),
        INDEX \`IDX_stock_entry_detail_batch_id\` (\`batch_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_stock_entry_detail_tenant\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_detail_stock_entry\` FOREIGN KEY (\`stock_entry_id\`) REFERENCES \`tabStockEntry\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_detail_item\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_detail_source_warehouse\` FOREIGN KEY (\`source_warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_detail_target_warehouse\` FOREIGN KEY (\`target_warehouse_id\`) REFERENCES \`tabWarehouse\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT \`FK_stock_entry_detail_batch\` FOREIGN KEY (\`batch_id\`) REFERENCES \`tabBatch\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE \`tabStockEntryDetail\``);
    await queryRunner.query(`DROP TABLE \`tabStockEntry\``);
    await queryRunner.query(`DROP TABLE \`tabSerialNo\``);
    await queryRunner.query(`DROP TABLE \`tabBatch\``);
    await queryRunner.query(`DROP TABLE \`tabBin\``);
    await queryRunner.query(`DROP TABLE \`tabWarehouse\``);
  }
}