import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTabWorkOrderTable1758247580419 implements MigrationInterface {
    name = 'CreateTabWorkOrderTable1758247580419'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tabUser\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(140) NOT NULL, \`first_name\` varchar(140) NOT NULL, \`last_name\` varchar(140) NULL, \`password\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`language\` varchar(10) NOT NULL DEFAULT 'en', \`time_zone\` varchar(50) NOT NULL DEFAULT 'Africa/Addis_Ababa', \`mobile_no\` varchar(140) NULL, \`role_profile_name\` varchar(140) NULL, \`creation\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, UNIQUE INDEX \`IDX_5dd4caf3cc4f6cb6647fc1f1e7\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabTenant\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`subdomain\` varchar(100) NOT NULL, \`status\` enum ('active', 'inactive', 'suspended') NOT NULL DEFAULT 'active', \`plan\` enum ('basic', 'premium', 'enterprise') NOT NULL DEFAULT 'basic', \`settings\` longtext NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`docstatus\` int NOT NULL DEFAULT '0', \`idx\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`modified_by\` varchar(140) NULL, UNIQUE INDEX \`IDX_a2e29961f7f743293fff382608\` (\`subdomain\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`valuationMethod\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`standardSellingRate\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`maxDiscount\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`isStockItem\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`autoCreateAssets\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`assetCategory\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`assetNamingSeries\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`allowAlternativeItem\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`includeItemInManufacturing\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`isSubContractedItem\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultMaterialRequestType\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultSupplier\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultExpenseAccount\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultIncomeAccount\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultBuyingCostCenter\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultSellingCostCenter\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`defaultWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`customerCode\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`customerItemName\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`publishedInWebsite\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`routeOfManufacturing\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`hasVariants\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`variantOf\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`webLongDescription\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`webShortDescription\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`websiteImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`thumbnailImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`showInWebsite\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`websiteWarehouseQty\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`websiteWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`websiteSpecifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`showVariantThumbnail\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`slideshow\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`websiteItemGroups\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`setMetaTags\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`metaTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`metaDescription\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`metaKeywords\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`stockUom\` \`stockUom\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`purchaseUom\` \`purchaseUom\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`salesUom\` \`salesUom\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`standardRate\` \`standardRate\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`lastPurchaseRate\` \`lastPurchaseRate\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`valuationRate\` \`valuationRate\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`minOrderQty\` \`minOrderQty\` decimal(18,6) NOT NULL DEFAULT '0.000000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`safetyStock\` \`safetyStock\` decimal(18,6) NOT NULL DEFAULT '0.000000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`leadTimeDays\` \`leadTimeDays\` decimal(18,6) NOT NULL DEFAULT '0.000000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`brand\` \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`itemGroup\` \`itemGroup\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`weightPerUnit\` \`weightPerUnit\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`weightUom\` \`weightUom\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`specifications\` \`specifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`qualityInspectionTemplate\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`qualityInspectionTemplate\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`inspectionRequiredBeforePurchase\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`inspectionRequiredBeforePurchase\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`inspectionRequiredBeforeDelivery\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`inspectionRequiredBeforeDelivery\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`createdById\` \`createdById\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`modifiedById\` \`modifiedById\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`created_by\` \`created_by\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`modified_by\` \`modified_by\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP FOREIGN KEY \`FK_bfb5656ffc6201cae6e24bcbbb5\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`requiredDate\` \`requiredDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`bomReference\` \`bomReference\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`warehouse\` \`warehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP COLUMN \`specifications\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD \`specifications\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`itemId\` \`itemId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`item_id\` \`item_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`operation\` \`operation\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`workstation\` \`workstation\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`machine\` \`machine\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`plannedStartTime\` \`plannedStartTime\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`plannedEndTime\` \`plannedEndTime\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`actualStartTime\` \`actualStartTime\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`actualEndTime\` \`actualEndTime\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`instructions\` \`instructions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`qualityParameters\` \`qualityParameters\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`timeLog\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`timeLog\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`qualityData\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`qualityData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`assignedToId\` \`assignedToId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completedById\` \`completedById\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completedAt\` \`completedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completed_by\` \`completed_by\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_448386053d54c62e8b976cc611e\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_ba9233bf837be1df36d25e3a939\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`bomNo\` \`bomNo\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`salesOrder\` \`salesOrder\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`project\` \`project\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`sourceWarehouse\` \`sourceWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`wipWarehouse\` \`wipWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`fgWarehouse\` \`fgWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`scrapWarehouse\` \`scrapWarehouse\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`plannedStartDate\` \`plannedStartDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`plannedEndDate\` \`plannedEndDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`expectedDeliveryDate\` \`expectedDeliveryDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`actualStartDate\` \`actualStartDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`actualEndDate\` \`actualEndDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`productionPlanId\` \`productionPlanId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`itemId\` \`itemId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`assignedToId\` \`assignedToId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`production_plan_id\` \`production_plan_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`item_id\` \`item_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`assigned_to\` \`assigned_to\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`priority\` \`priority\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approvedById\` \`approvedById\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approvedAt\` \`approvedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`startedAt\` \`startedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`completedAt\` \`completedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approved_by\` \`approved_by\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_d7d027b642add7f0e77c36b874f\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_25a958155bb9a9d741210749e07\` FOREIGN KEY (\`created_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_2b4616ac46567ad47e0026030d2\` FOREIGN KEY (\`modified_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD CONSTRAINT \`FK_bfb5656ffc6201cae6e24bcbbb5\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD CONSTRAINT \`FK_def951a7aee18bbe2a61a6de374\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD CONSTRAINT \`FK_7b6382cc338027d797c02c08887\` FOREIGN KEY (\`assigned_to\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD CONSTRAINT \`FK_12c4b7d53c702fa1175c8ea1547\` FOREIGN KEY (\`completed_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD CONSTRAINT \`FK_b027f53a2f4cc789a79d76f45d2\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_0059be3d968bef25dcf779f043e\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_448386053d54c62e8b976cc611e\` FOREIGN KEY (\`production_plan_id\`) REFERENCES \`production_plans\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_ba9233bf837be1df36d25e3a939\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_b520b436fb6ce9fabb3de65aeb7\` FOREIGN KEY (\`created_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_f10ffb04ddc99112db4523117c4\` FOREIGN KEY (\`assigned_to\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD CONSTRAINT \`FK_0a60dfceafde9f802bdf5443304\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tabTenant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD CONSTRAINT \`FK_aeb91fc016c969848a5db32bb52\` FOREIGN KEY (\`created_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD CONSTRAINT \`FK_b19871f2d11ca7f4ee5e21db73e\` FOREIGN KEY (\`approved_by\`) REFERENCES \`tabUser\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP FOREIGN KEY \`FK_b19871f2d11ca7f4ee5e21db73e\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP FOREIGN KEY \`FK_aeb91fc016c969848a5db32bb52\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP FOREIGN KEY \`FK_0a60dfceafde9f802bdf5443304\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_f10ffb04ddc99112db4523117c4\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_b520b436fb6ce9fabb3de65aeb7\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_ba9233bf837be1df36d25e3a939\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_448386053d54c62e8b976cc611e\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP FOREIGN KEY \`FK_0059be3d968bef25dcf779f043e\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP FOREIGN KEY \`FK_b027f53a2f4cc789a79d76f45d2\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP FOREIGN KEY \`FK_12c4b7d53c702fa1175c8ea1547\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP FOREIGN KEY \`FK_7b6382cc338027d797c02c08887\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP FOREIGN KEY \`FK_def951a7aee18bbe2a61a6de374\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP FOREIGN KEY \`FK_bfb5656ffc6201cae6e24bcbbb5\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_2b4616ac46567ad47e0026030d2\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_25a958155bb9a9d741210749e07\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_d7d027b642add7f0e77c36b874f\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approved_by\` \`approved_by\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`completedAt\` \`completedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`startedAt\` \`startedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approvedAt\` \`approvedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`approvedById\` \`approvedById\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD \`tenant_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`priority\` \`priority\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plans\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`assigned_to\` \`assigned_to\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`item_id\` \`item_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`production_plan_id\` \`production_plan_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`assignedToId\` \`assignedToId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`itemId\` \`itemId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`productionPlanId\` \`productionPlanId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD \`tenant_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`actualEndDate\` \`actualEndDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`actualStartDate\` \`actualStartDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`expectedDeliveryDate\` \`expectedDeliveryDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`plannedEndDate\` \`plannedEndDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`plannedStartDate\` \`plannedStartDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`scrapWarehouse\` \`scrapWarehouse\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`fgWarehouse\` \`fgWarehouse\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`wipWarehouse\` \`wipWarehouse\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`sourceWarehouse\` \`sourceWarehouse\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`project\` \`project\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`salesOrder\` \`salesOrder\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`bomNo\` \`bomNo\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_ba9233bf837be1df36d25e3a939\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD CONSTRAINT \`FK_448386053d54c62e8b976cc611e\` FOREIGN KEY (\`production_plan_id\`) REFERENCES \`production_plans\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completed_by\` \`completed_by\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completedAt\` \`completedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`completedById\` \`completedById\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`assignedToId\` \`assignedToId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`qualityData\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`qualityData\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`timeLog\``);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` ADD \`timeLog\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`qualityParameters\` \`qualityParameters\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`instructions\` \`instructions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`actualEndTime\` \`actualEndTime\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`actualStartTime\` \`actualStartTime\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`plannedEndTime\` \`plannedEndTime\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`plannedStartTime\` \`plannedStartTime\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`machine\` \`machine\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`workstation\` \`workstation\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`operation\` \`operation\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`item_id\` \`item_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`itemId\` \`itemId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP COLUMN \`specifications\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD \`specifications\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`warehouse\` \`warehouse\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`bomReference\` \`bomReference\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`requiredDate\` \`requiredDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` ADD CONSTRAINT \`FK_bfb5656ffc6201cae6e24bcbbb5\` FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`modified_by\` \`modified_by\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`created_by\` \`created_by\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`modifiedById\` \`modifiedById\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`createdById\` \`createdById\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`inspectionRequiredBeforeDelivery\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`inspectionRequiredBeforeDelivery\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`inspectionRequiredBeforePurchase\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`inspectionRequiredBeforePurchase\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`qualityInspectionTemplate\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`qualityInspectionTemplate\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`specifications\` \`specifications\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`weightUom\` \`weightUom\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`weightPerUnit\` \`weightPerUnit\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`itemGroup\` \`itemGroup\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`brand\` \`brand\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`leadTimeDays\` \`leadTimeDays\` decimal(15,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`safetyStock\` \`safetyStock\` decimal(15,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`minOrderQty\` \`minOrderQty\` decimal(15,4) NOT NULL DEFAULT '0.0000'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`valuationRate\` \`valuationRate\` decimal(15,4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`lastPurchaseRate\` \`lastPurchaseRate\` decimal(15,4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`standardRate\` \`standardRate\` decimal(15,4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`salesUom\` \`salesUom\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`purchaseUom\` \`purchaseUom\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`stockUom\` \`stockUom\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_order_tasks\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`production_plan_items\` DROP COLUMN \`tenant_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`metaKeywords\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`metaDescription\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`metaTitle\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`setMetaTags\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`websiteItemGroups\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`slideshow\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`showVariantThumbnail\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`websiteSpecifications\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`websiteWarehouse\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`websiteWarehouseQty\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`showInWebsite\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`thumbnailImage\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`websiteImage\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`webShortDescription\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`webLongDescription\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`variantOf\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`hasVariants\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`routeOfManufacturing\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`publishedInWebsite\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`customerItemName\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`customerCode\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultWarehouse\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultSellingCostCenter\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultBuyingCostCenter\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultIncomeAccount\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultExpenseAccount\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultSupplier\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`defaultMaterialRequestType\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`isSubContractedItem\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`includeItemInManufacturing\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`allowAlternativeItem\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`assetNamingSeries\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`assetCategory\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`autoCreateAssets\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`isStockItem\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`maxDiscount\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`standardSellingRate\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`valuationMethod\``);
        await queryRunner.query(`ALTER TABLE \`production_plans\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`work_orders\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`tenant_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_a2e29961f7f743293fff382608\` ON \`tabTenant\``);
        await queryRunner.query(`DROP TABLE \`tabTenant\``);
        await queryRunner.query(`DROP INDEX \`IDX_5dd4caf3cc4f6cb6647fc1f1e7\` ON \`tabUser\``);
        await queryRunner.query(`DROP TABLE \`tabUser\``);
    }

}
